# Generated by Django 5.1.2 on 2024-10-23 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_ps', models.CharField(choices=[('Ideaforge', 'Ideaforge'), ('Zelta', 'Zelta'), ('Pathway', 'Pathway'), ('ISRO', 'ISRO')], max_length=50)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_item', models.CharField(choices=[('Pizza', 'Pizza'), ('Burger', 'Burger'), ('Salad', 'Salad'), ('Pasta', 'Pasta')], max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='booking.foodbooking')),
            ],
        ),
    ]
